# Generated by Django 6.0.2 on 2026-02-22 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion_min',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='funcion',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
